"use client";

import { apiFetch } from "@/api";
import { FormEvent, useEffect, useMemo, useState } from "react";

const apiUrl=process.env.NEXT_PUBLIC_API_URL??"/api/v1";
type Tipo="CLIENTE"|"PROVEEDOR";
type LineaOrigen={detalle_id:string;codigo:string;descripcion:string;cantidad_disponible:string;importe_unitario_bruto:string};
type Origen={id:string;socio_nombre:string;numero:string;fecha:string;total:string;saldo_pendiente:string;lineas:LineaOrigen[]};
type Nota={id:string;numero:number;socio_nombre:string;documento_origen:string;numero_externo:string|null;motivo:string;afecta_stock:boolean;total_bruto:string;fecha_realizacion:string};
const dinero=(v:string|number)=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS"}).format(Number(v||0));
const fecha=(v:string)=>new Date(v).toLocaleString("es-AR");

export default function NotasCredito(){
 const[tipo,setTipo]=useState<Tipo>("CLIENTE"),[origenes,setOrigenes]=useState<Origen[]>([]),[notas,setNotas]=useState<Nota[]>([]),[buscar,setBuscar]=useState(""),[origenId,setOrigenId]=useState(""),[cantidades,setCantidades]=useState<Record<string,string>>({}),[motivo,setMotivo]=useState(""),[numeroExterno,setNumeroExterno]=useState(""),[afectaStock,setAfectaStock]=useState(true),[mensaje,setMensaje]=useState(""),[procesando,setProcesando]=useState(false),[confirmando,setConfirmando]=useState(false);
 async function cargar(t:Tipo=tipo){const[ro,rn]=await Promise.all([apiFetch(`${apiUrl}/notas-credito/origenes?tipo=${t}`,{credentials:"include"}),apiFetch(`${apiUrl}/notas-credito?tipo=${t}`,{credentials:"include"})]);if(ro.ok)setOrigenes(await ro.json());else setMensaje((await ro.json().catch(()=>null))?.detail??"No se pudieron consultar los comprobantes");if(rn.ok)setNotas(await rn.json())}
 useEffect(()=>{const inicial=new URLSearchParams(window.location.search).get("tipo")==="PROVEEDOR"?"PROVEEDOR":"CLIENTE";setTipo(inicial);void cargar(inicial)},[]);
 function cambiarTipo(t:Tipo){setTipo(t);setOrigenId("");setCantidades({});setBuscar("");setMensaje("");void cargar(t)}
 const origen=origenes.find(x=>x.id===origenId);
 const filtrados=useMemo(()=>{const ts=buscar.toLowerCase().trim().split(/\s+/).filter(Boolean);return origenes.filter(x=>ts.every(t=>`${x.numero} ${x.socio_nombre}`.toLowerCase().includes(t)))},[buscar,origenes]);
 const total=origen?.lineas.reduce((s,x)=>s+Number(cantidades[x.detalle_id]||0)*Number(x.importe_unitario_bruto),0)??0;
 const lineas=origen?.lineas.filter(x=>Number(cantidades[x.detalle_id])>0).map(x=>({detalle_origen_id:x.detalle_id,cantidad_base:Number(cantidades[x.detalle_id])}))??[];
 function preparar(e:FormEvent){e.preventDefault();setMensaje("");if(!origen||!lineas.length||motivo.trim().length<5){setMensaje("Seleccione un comprobante, cantidades y un motivo de al menos 5 caracteres");return}if(tipo==="PROVEEDOR"&&!numeroExterno.trim()){setMensaje("Indique el numero de nota de credito del proveedor");return}setConfirmando(true)}
 async function confirmar(){setProcesando(true);setConfirmando(false);const r=await apiFetch(`${apiUrl}/notas-credito`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({tipo,documento_origen_id:origenId,lineas,motivo,afecta_stock:afectaStock,numero_externo:tipo==="PROVEEDOR"?numeroExterno:null})});const d=await r.json().catch(()=>null);setProcesando(false);if(!r.ok){setMensaje(d?.detail??"No se pudo crear la nota de credito");return}setMensaje(`Nota de credito NC ${String(d.numero).padStart(8,"0")} confirmada por ${dinero(d.total_bruto)}`);setOrigenId("");setCantidades({});setMotivo("");setNumeroExterno("");await cargar()}
 return <main className="p-6 sm:p-9"><header className="flex flex-wrap items-end justify-between gap-4 border-b pb-5"><div><p className="text-xs font-bold uppercase tracking-widest text-[var(--marca)]">Cuentas corrientes</p><h1 className="text-3xl font-semibold">Notas de credito</h1><p className="text-sm text-[var(--texto-suave)]">Acreditacion parcial o total contra el comprobante original, con devolucion de stock opcional.</p></div><div className="flex rounded-xl border bg-white p-1"><button onClick={()=>cambiarTipo("CLIENTE")} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tipo==="CLIENTE"?"bg-[var(--marca)] text-white":""}`}>Clientes / POS</button><button onClick={()=>cambiarTipo("PROVEEDOR")} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tipo==="PROVEEDOR"?"bg-[var(--marca)] text-white":""}`}>Proveedores</button></div></header>
 {mensaje&&<p className="mt-4 rounded-xl bg-[var(--marca-clara)] p-3 text-sm font-semibold">{mensaje}</p>}
 <form onSubmit={preparar} className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">1 · Comprobante original</h2><input value={buscar} onChange={e=>setBuscar(e.target.value)} placeholder="Cliente/proveedor o numero de comprobante" className="mt-3 w-full rounded-xl border p-3"/><div className="mt-3 max-h-64 space-y-2 overflow-auto">{filtrados.map(x=><button type="button" key={x.id} onClick={()=>{setOrigenId(x.id);setCantidades({})}} className={`w-full rounded-xl border p-3 text-left text-sm ${origenId===x.id?"border-[var(--marca)] bg-[var(--marca-clara)]":""}`}><b>{x.numero} · {x.socio_nombre}</b><small className="block text-[var(--texto-suave)]">{fecha(x.fecha)} · Total {dinero(x.total)} · Saldo {dinero(x.saldo_pendiente)}</small></button>)}{!filtrados.length&&<p className="p-5 text-center text-sm text-[var(--texto-suave)]">No hay comprobantes con cantidades disponibles.</p>}</div>
 {origen&&<div className="mt-5 overflow-x-auto"><h2 className="font-semibold">2 · Cantidades a acreditar</h2><table className="mt-2 w-full min-w-[680px] text-left text-sm"><thead><tr><th className="p-2">Articulo</th><th>Disponible</th><th>Importe historico</th><th>A acreditar</th><th className="text-right">Subtotal</th></tr></thead><tbody>{origen.lineas.map(x=><tr key={x.detalle_id} className="border-t"><td className="p-2"><b>{x.codigo}</b><small className="block">{x.descripcion}</small></td><td>{x.cantidad_disponible}</td><td>{dinero(x.importe_unitario_bruto)}</td><td><input type="number" min="0" max={x.cantidad_disponible} step="0.000001" value={cantidades[x.detalle_id]??""} onChange={e=>setCantidades({...cantidades,[x.detalle_id]:e.target.value})} className="w-32 rounded-lg border p-2"/></td><td className="text-right font-semibold">{dinero(Number(cantidades[x.detalle_id]||0)*Number(x.importe_unitario_bruto))}</td></tr>)}</tbody></table></div>}</section>
 <aside className="h-fit rounded-2xl border bg-white p-5"><h2 className="font-semibold">3 · Confirmacion</h2>{tipo==="PROVEEDOR"&&<label className="mt-4 block text-sm">Numero emitido por el proveedor<input required value={numeroExterno} onChange={e=>setNumeroExterno(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label>}<label className="mt-4 block text-sm">Motivo<textarea required minLength={5} value={motivo} onChange={e=>setMotivo(e.target.value)} className="mt-1 w-full rounded-xl border p-3" rows={3}/></label><label className="mt-4 flex items-start gap-3 rounded-xl bg-[var(--fondo)] p-3 text-sm"><input type="checkbox" checked={afectaStock} onChange={e=>setAfectaStock(e.target.checked)} className="mt-1"/><span><b>Devolver mercaderia</b><small className="block text-[var(--texto-suave)]">{tipo==="CLIENTE"?"Reingresa al almacen original.":"Descuenta del almacen para devolver al proveedor."}</small></span></label><div className="mt-4 rounded-xl bg-[var(--marca-clara)] p-4"><small>Total de la nota</small><b className="block text-2xl text-[var(--marca)]">{dinero(total)}</b><small>Se aplica primero al saldo del comprobante. El excedente queda disponible.</small></div><button disabled={procesando||!lineas.length} className="mt-4 w-full rounded-xl bg-[var(--marca)] px-4 py-3 font-semibold text-white disabled:opacity-40">{procesando?"Confirmando...":"Crear nota de credito"}</button></aside></form>
 <section className="mt-5 rounded-2xl border bg-white p-5"><h2 className="font-semibold">Historico de notas de credito</h2><div className="mt-3 overflow-x-auto"><table data-exportar-excel="true" className="w-full min-w-[850px] text-left text-sm"><thead><tr><th className="p-2">Fecha</th><th>Numero</th><th>Socio</th><th>Origen</th><th>Motivo</th><th>Stock</th><th className="text-right">Total</th><th></th></tr></thead><tbody>{notas.map(x=><tr key={x.id} className="border-t"><td className="p-2">{fecha(x.fecha_realizacion)}</td><td>NC {String(x.numero).padStart(8,"0")}{x.numero_externo?` · ${x.numero_externo}`:""}</td><td>{x.socio_nombre}</td><td>{x.documento_origen}</td><td>{x.motivo}</td><td>{x.afecta_stock?"SI":"NO"}</td><td className="text-right font-semibold">{dinero(x.total_bruto)}</td><td><button type="button" onClick={()=>window.open(`${apiUrl}/notas-credito/${x.id}/imprimir`,"_blank")} className="rounded-lg border px-3 py-2">Imprimir</button></td></tr>)}</tbody></table></div></section>
 {confirmando&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4" role="dialog" aria-modal="true"><section className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-semibold">Confirmar nota de credito</h2><p className="mt-3 text-sm">Se generara una nota por <b>{dinero(total)}</b> contra <b>{origen?.numero}</b>. {afectaStock?"Tambien se registrara la devolucion de mercaderia.":"No se modificara el stock."}</p><p className="mt-2 text-sm text-red-700">Una nota confirmada queda en el historico y no se elimina.</p><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setConfirmando(false)} className="rounded-xl border px-4 py-2">Cancelar</button><button type="button" onClick={()=>void confirmar()} className="rounded-xl bg-[var(--marca)] px-4 py-2 font-semibold text-white">Confirmar definitivamente</button></div></section></div>}</main>
}
