"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

const apiUrl=process.env.NEXT_PUBLIC_API_URL??"/api/v1";
type Punto={id:string;codigo:string;descripcion:string;letra:string;tipo_documento:string;almacen_id:string;ultimo_numero:number;activo:boolean};
type Caja={id:string;punto_venta_id:string;codigo:string;descripcion:string;activo:boolean};
type Almacen={id:string;codigo:string;descripcion:string;activo:boolean};

export default function ConfiguracionPos(){
 const[puntos,setPuntos]=useState<Punto[]>([]),[cajas,setCajas]=useState<Caja[]>([]),[almacenes,setAlmacenes]=useState<Almacen[]>([]),[mensaje,setMensaje]=useState("");
 const[codigoPunto,setCodigoPunto]=useState(""),[descripcionPunto,setDescripcionPunto]=useState(""),[almacen,setAlmacen]=useState("");
 const[puntoCaja,setPuntoCaja]=useState(""),[codigoCaja,setCodigoCaja]=useState(""),[descripcionCaja,setDescripcionCaja]=useState("");
 const cargar=useCallback(async()=>{const[ rp,rc,ra]=await Promise.all([fetch(`${apiUrl}/articulos/pos/configuracion/puntos-venta`,{credentials:"include"}),fetch(`${apiUrl}/articulos/pos/configuracion/cajas`,{credentials:"include"}),fetch(`${apiUrl}/articulos/almacenes`,{credentials:"include"})]);if(rp.ok)setPuntos(await rp.json());if(rc.ok)setCajas(await rc.json());if(ra.ok)setAlmacenes(await ra.json())},[]);
 useEffect(()=>{const t=window.setTimeout(()=>void cargar(),0);return()=>window.clearTimeout(t)},[cargar]);
 async function crearPunto(e:FormEvent){e.preventDefault();const r=await fetch(`${apiUrl}/articulos/pos/configuracion/puntos-venta`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({codigo:codigoPunto,descripcion:descripcionPunto,almacen_id:almacen})});const d=await r.json();setMensaje(r.ok?"Punto de venta creado":d.detail??"No se pudo crear");if(r.ok){setCodigoPunto("");setDescripcionPunto("");await cargar()}}
 async function crearCaja(e:FormEvent){e.preventDefault();const r=await fetch(`${apiUrl}/articulos/pos/configuracion/cajas`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({punto_venta_id:puntoCaja,codigo:codigoCaja,descripcion:descripcionCaja})});const d=await r.json();setMensaje(r.ok?"Caja creada":d.detail??"No se pudo crear");if(r.ok){setCodigoCaja("");setDescripcionCaja("");await cargar()}}
 return <main className="listas-precios-pagina p-6 sm:p-9"><header className="border-b pb-5"><p className="text-xs font-bold uppercase tracking-widest text-[var(--marca)]">Ventas · Administracion</p><h1 className="text-3xl font-semibold">Puntos de venta y cajas</h1><p className="text-sm text-[var(--texto-suave)]">Documento configurado: PRESUPUESTO · Letra T.</p></header>{mensaje&&<p className="mt-4 rounded-xl bg-[var(--marca-clara)] p-3 text-sm">{mensaje}</p>}
 <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-semibold">Puntos de venta</h2><form onSubmit={crearPunto} className="mt-4 grid gap-3 sm:grid-cols-2"><label>Codigo<input required maxLength={4} className="mt-1 w-full rounded-xl border p-3" value={codigoPunto} onChange={e=>setCodigoPunto(e.target.value)}/></label><label>Descripcion<input required className="mt-1 w-full rounded-xl border p-3" value={descripcionPunto} onChange={e=>setDescripcionPunto(e.target.value)}/></label><label className="sm:col-span-2">Almacen<select required className="mt-1 w-full rounded-xl border p-3" value={almacen} onChange={e=>setAlmacen(e.target.value)}><option value="">Seleccionar</option>{almacenes.filter(x=>x.activo).map(x=><option key={x.id} value={x.id}>{x.codigo} - {x.descripcion}</option>)}</select></label><button className="sm:col-span-2 justify-self-end rounded-xl bg-[var(--marca)] px-4 py-2 font-semibold text-white">Crear punto</button></form><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Codigo</th><th>Documento</th><th>Ultimo</th><th>Estado</th></tr></thead><tbody>{puntos.map(x=><tr className="border-t" key={x.id}><td className="py-3 font-semibold">{x.codigo}</td><td>{x.tipo_documento} {x.letra}</td><td>{String(x.ultimo_numero).padStart(8,"0")}</td><td>{x.activo?"ACTIVO":"INACTIVO"}</td></tr>)}</tbody></table></div></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-semibold">Cajas</h2><form onSubmit={crearCaja} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2">Punto de venta<select required className="mt-1 w-full rounded-xl border p-3" value={puntoCaja} onChange={e=>setPuntoCaja(e.target.value)}><option value="">Seleccionar</option>{puntos.filter(x=>x.activo).map(x=><option key={x.id} value={x.id}>{x.codigo} - {x.descripcion}</option>)}</select></label><label>Codigo<input required className="mt-1 w-full rounded-xl border p-3" value={codigoCaja} onChange={e=>setCodigoCaja(e.target.value)}/></label><label>Descripcion<input required className="mt-1 w-full rounded-xl border p-3" value={descripcionCaja} onChange={e=>setDescripcionCaja(e.target.value)}/></label><button className="sm:col-span-2 justify-self-end rounded-xl bg-[var(--marca)] px-4 py-2 font-semibold text-white">Crear caja</button></form><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Caja</th><th>Punto</th><th>Estado</th></tr></thead><tbody>{cajas.map(x=><tr className="border-t" key={x.id}><td className="py-3 font-semibold">{x.codigo} - {x.descripcion}</td><td>{puntos.find(p=>p.id===x.punto_venta_id)?.codigo}</td><td>{x.activo?"ACTIVA":"INACTIVA"}</td></tr>)}</tbody></table></div></section></div></main>
}
