"use client";

import type { SeccionManual } from "@/manual/contenido";

function CabeceraVista({titulo, subtitulo}:{titulo:string;subtitulo:string}) {
  return <header className="manual-vista-cabecera"><div><small>MORITA ERP</small><strong>{titulo}</strong><span>{subtitulo}</span></div><div className="manual-vista-acciones"><i>☀</i><i>🧠</i></div></header>;
}

function TablaVista({columnas,filas}:{columnas:string[];filas:string[][]}) {
  return <div className="manual-vista-tabla"><div className="manual-vista-fila manual-vista-titulos">{columnas.map(c=><b key={c}>{c}</b>)}</div>{filas.map((fila,i)=><div className="manual-vista-fila" key={i}>{fila.map((valor,j)=><span key={`${i}-${j}`}>{valor}</span>)}</div>)}</div>;
}

export default function CapturaManual({seccion}:{seccion:SeccionManual}) {
  let contenido: React.ReactNode;
  if(seccion.vista==="inicio") contenido=<><CabeceraVista titulo={seccion.id==="panel"?"Panel principal":"Bienvenido a Morita"} subtitulo="La información visible depende de tus permisos"/><div className="manual-vista-tarjetas"><div><small>VENTAS</small><b>$ 203.850,00</b></div><div><small>STOCK</small><b>1.284 u.</b></div><div><small>CUENTAS</small><b>Al día</b></div></div></>;
  else if(seccion.vista==="maestros") contenido=<><CabeceraVista titulo="Socios de negocio" subtitulo="Clientes y proveedores"/><div className="manual-vista-busqueda">Buscar por nombre, código o documento <button>Nuevo</button></div><TablaVista columnas={["CÓDIGO","NOMBRE","TIPO","ESTADO"]} filas={[["00015","FERNANDO MONTERO","CLIENTE","ACTIVO"],["00028","DISTRIBUIDORA SUR","PROVEEDOR","ACTIVO"]]}/></>;
  else if(seccion.vista==="stock") contenido=<><CabeceraVista titulo="Control de stock" subtitulo="Existencias y movimientos por almacén"/><div className="manual-vista-filtros"><span>ALM001 - ALMACÉN PRINCIPAL</span><span>Buscar producto...</span></div><TablaVista columnas={["ARTÍCULO","ACTUAL","RESERVADO","DISPONIBLE"]} filas={[["00001 - PRODUCTO DE PRUEBA","24,000","2,000","22,000"],["00002 - ARTÍCULO DEMO","18,500","0,000","18,500"]]}/></>;
  else if(seccion.vista==="compras") contenido=<><CabeceraVista titulo="Compras" subtitulo="Ingresos, facturas y reposición"/><div className="manual-vista-pestanas"><b>Ingresos</b><span>Facturas</span><span>Rotación y reposición</span></div><div className="manual-vista-resumen"><small>PROYECCIÓN</small><strong>30 días</strong><small>SUGERENCIA</small><strong>42,000 u.</strong></div><TablaVista columnas={["PRODUCTO","ROTACIÓN","DISPONIBLE","COMPRAR"]} filas={[["PRODUCTO DE PRUEBA","1,800/día","12,000","42,000"]]}/></>;
  else if(seccion.vista==="pos") contenido=<><CabeceraVista titulo="Punto de venta" subtitulo="0001 · CAJA01 · Caja de ADMIN"/><div className="manual-vista-pos"><div><label>Cliente</label><span>CONSUMIDOR FINAL</span><label>Escanear o buscar producto</label><span className="manual-vista-foco">Código, descripción o barra <kbd>F2</kbd></span><TablaVista columnas={["ARTÍCULO","CANT.","PRECIO","TOTAL"]} filas={[["PRODUCTO DE PRUEBA","2,000","$ 2.600,00","$ 5.200,00"]]}/></div><aside><small>TOTAL DE LA VENTA</small><strong>$ 5.200,00</strong><button>COBRAR · F10</button></aside></div></>;
  else if(seccion.vista==="notas") contenido=<><CabeceraVista titulo="Notas de crédito" subtitulo="Comprobante vinculado y motivo"/><div className="manual-vista-filtros"><span>Factura T 0001-00000005</span><span>Motivo: DIFERENCIA DE PRECIO</span></div><TablaVista columnas={["ARTÍCULO","CANTIDAD","IMPORTE","MARGEN"]} filas={[["PRODUCTO DE PRUEBA","1,000","-$ 600,00","-$ 115,00"]]}/><div className="manual-vista-confirmar">Factura vinculada: T 0001-00000005 <button>Emitir nota</button></div></>;
  else if(seccion.vista==="tesoreria") contenido=<><CabeceraVista titulo="Tesorería" subtitulo="Cuentas corrientes, caja y cierres"/><div className="manual-vista-pestanas"><b>Cuentas corrientes</b><span>Caja y arqueo</span><span>Historial de cierres</span></div><div className="manual-vista-tarjetas"><div><small>TOTAL POR COBRAR</small><b>$ 56.250,00</b></div><div><small>SALDO A FAVOR</small><b>$ 94.800,00</b></div></div><TablaVista columnas={["CLIENTE","DEUDA","A FAVOR","ACCIÓN"]} filas={[["FERNANDO MONTERO","$ 56.250,00","$ 94.800,00","Abrir cuenta"]]}/></>;
  else if(seccion.vista==="informes") contenido=<><CabeceraVista titulo="Informes" subtitulo="Flujo de dinero, ventas y márgenes"/><div className="manual-vista-filtros"><span>Desde 01/08/2026</span><span>Hasta 31/08/2026</span><button>▣ Excel</button></div><div className="manual-vista-tarjetas"><div><small>VENTAS NETAS</small><b>$ 203.850,00</b></div><div><small>MARGEN</small><b>$ 40.770,00</b></div><div><small>MARGEN %</small><b>20,00 %</b></div></div><TablaVista columnas={["COMPROBANTE","CLIENTE","IMPORTE","MARGEN %"]} filas={[["T 0001-00000005","FERNANDO MONTERO","$ 2.600,00","23,08 %"]]}/></>;
  else if(seccion.vista==="accesos") contenido=<><CabeceraVista titulo="Usuarios y permisos" subtitulo="Accesos expresamente autorizados"/><TablaVista columnas={["USUARIO","PERFIL","ESTADO","ACCIÓN"]} filas={[["CAJERO01","CAJERO","ACTIVO","Editar"],["ADMIN","ADMINISTRADOR","ACTIVO","Editar"]]}/><div className="manual-vista-permisos"><span>✓ Operar caja</span><span>✓ Cerrar caja</span><span>○ Emitir notas de crédito</span></div></>;
  else contenido=<><CabeceraVista titulo="Impresión y exportación" subtitulo="Vista previa o salida directa"/><div className="manual-vista-impresion"><div><b>Vista previa</b><span>Abre el comprobante antes de imprimir</span></div><div className="activo"><b>Impresión directa</b><span>Imprime y envía la señal de corte</span></div><button>▣ Descargar Excel</button></div></>;

  return <figure className="manual-captura"><div className="manual-captura-marco">{contenido}</div><figcaption>Vista guiada del módulo · datos demostrativos</figcaption></figure>;
}
