"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

const apiUrl=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000/api/v1";
type Indice="usuarios"|"perfiles"|"permisos";
type Permiso={id:string;codigo:string;modulo:string;accion:string;descripcion:string};
type Perfil={id:string;nombre:string;descripcion:string|null;activo:boolean;es_sistema:boolean;permiso_ids:string[]};
type Usuario={id:string;nombre_usuario:string;activo:boolean;es_administrador:boolean;debe_cambiar_contrasena:boolean;perfil_ids:string[];permiso_ids:string[]};

export default function ConfiguracionAccesos(){
 const router=useRouter();const[indice,setIndice]=useState<Indice>("usuarios"),[permisos,setPermisos]=useState<Permiso[]>([]),[perfiles,setPerfiles]=useState<Perfil[]>([]),[usuarios,setUsuarios]=useState<Usuario[]>([]),[mensaje,setMensaje]=useState(""),[cargando,setCargando]=useState(true),[editando,setEditando]=useState<Usuario|null>(null);
 const cargar=useCallback(async()=>{const[rp,rf,ru]=await Promise.all([fetch(`${apiUrl}/administracion/accesos/permisos`,{credentials:"include"}),fetch(`${apiUrl}/administracion/accesos/perfiles`,{credentials:"include"}),fetch(`${apiUrl}/administracion/accesos/usuarios`,{credentials:"include"})]);if([rp,rf,ru].some(r=>r.status===401||r.status===403)){router.replace("/panel");return}if(rp.ok)setPermisos(await rp.json());if(rf.ok)setPerfiles(await rf.json());if(ru.ok)setUsuarios(await ru.json());setCargando(false)},[router]);
 useEffect(()=>{const t=window.setTimeout(()=>void cargar(),0);return()=>window.clearTimeout(t)},[cargar]);
 if(cargando)return <main className="grid min-h-screen place-items-center text-sm">Cargando accesos...</main>;
 const indices:[Indice,string,string][]=[["usuarios","Usuarios","Altas y administracion"],["perfiles","Perfiles","Grupos de permisos"],["permisos","Permisos","Indice por modulo"]];
 return <main className="min-h-screen p-6 sm:p-8"><section><header className="border-b border-[var(--borde)] pb-5"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--marca)]">Configuracion</p><h1 className="mt-1 text-2xl font-semibold">Accesos</h1></header>{mensaje&&<p className="mt-4 rounded-xl bg-[var(--marca-clara)] p-3 text-sm">{mensaje}</p>}<div className="mt-6 grid gap-6 md:grid-cols-[220px_1fr]"><aside className="h-fit rounded-2xl border border-[var(--borde)] bg-white p-3"><p className="px-3 py-2 text-xs font-semibold uppercase tracking-[.12em] text-[var(--texto-suave)]">Indices</p>{indices.map(([id,nombre,detalle])=><button className={`mb-1 w-full rounded-xl px-3 py-2 text-left ${indice===id?"bg-[var(--marca-clara)] text-[var(--marca)]":"hover:bg-[var(--fondo)]"}`} key={id} onClick={()=>setIndice(id)}><b className="block text-sm">{nombre}</b><small className="text-xs opacity-70">{detalle}</small></button>)}</aside><section>{indice==="usuarios"&&<Usuarios usuarios={usuarios} perfiles={perfiles} abrir={setEditando} recargar={cargar} informar={setMensaje}/>} {indice==="perfiles"&&<Perfiles perfiles={perfiles} permisos={permisos} recargar={cargar} informar={setMensaje}/>} {indice==="permisos"&&<Permisos permisos={permisos}/>}</section></div>{editando&&<EditorUsuario usuario={editando} perfiles={perfiles} permisos={permisos} cerrar={()=>setEditando(null)} recargar={cargar} informar={setMensaje}/>}</section></main>;
}

function Usuarios({usuarios,perfiles,abrir,recargar,informar}:{usuarios:Usuario[];perfiles:Perfil[];abrir:(u:Usuario)=>void;recargar:()=>Promise<void>;informar:(m:string)=>void}){
 const[nuevo,setNuevo]=useState(false),[nombre,setNombre]=useState(""),[clave,setClave]=useState(""),[perfilIds,setPerfilIds]=useState<string[]>([]),[admin,setAdmin]=useState(false);
 async function crear(e:FormEvent){e.preventDefault();const r=await fetch(`${apiUrl}/administracion/accesos/usuarios`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({nombre_usuario:nombre,contrasena_temporal:clave,es_administrador:admin,perfil_ids:perfilIds,permiso_ids:[]})});const d=await r.json();if(!r.ok){informar(d.detail??"NO SE PUDO CREAR");return}setNombre("");setClave("");setPerfilIds([]);setNuevo(false);informar("USUARIO CREADO");await recargar()}
 async function eliminar(u:Usuario){if(!window.confirm(`¿Eliminar el acceso de ${u.nombre_usuario}?`))return;const r=await fetch(`${apiUrl}/administracion/accesos/usuarios/${u.id}`,{method:"DELETE",credentials:"include"});if(!r.ok){const d=await r.json();informar(d.detail??"NO SE PUDO ELIMINAR");return}informar("USUARIO DESACTIVADO");await recargar()}
 return <section className="rounded-2xl border border-[var(--borde)] bg-white p-5"><header className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Usuarios</h2><p className="text-xs text-[var(--texto-suave)]">Edicion y eliminacion disponibles en cada fila.</p></div><button className="rounded-xl bg-[var(--marca)] px-4 py-2 text-sm font-semibold text-white" onClick={()=>setNuevo(!nuevo)}>Nuevo usuario</button></header>{nuevo&&<form className="mt-5 grid gap-3 rounded-xl bg-[var(--fondo)] p-4 sm:grid-cols-2" onSubmit={crear}><Campo titulo="Usuario" valor={nombre} cambiar={setNombre}/><Campo titulo="Contraseña temporal" valor={clave} cambiar={setClave} tipo="password"/><div className="sm:col-span-2">{perfiles.filter(p=>p.activo).map(p=><Check key={p.id} texto={p.nombre} valor={perfilIds.includes(p.id)} cambiar={v=>setPerfilIds(v?[...perfilIds,p.id]:perfilIds.filter(id=>id!==p.id))}/>)}</div><Check texto="Administrador" valor={admin} cambiar={setAdmin}/><button className="rounded-xl bg-[var(--marca)] px-4 py-2 text-sm text-white">Crear</button></form>}<div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-[var(--texto-suave)]"><tr><th className="py-3">Usuario</th><th>Tipo</th><th>Perfiles</th><th>Estado</th><th className="w-48">Acciones</th></tr></thead><tbody>{usuarios.map(u=><tr className="border-b border-[var(--borde)]" key={u.id}><td className="py-3 font-semibold">{u.nombre_usuario}</td><td>{u.es_administrador?"Administrador":"Usuario"}</td><td>{u.perfil_ids.length}</td><td>{u.activo?"Activo":"Inactivo"}</td><td><div className="flex gap-2 py-2"><button className="rounded-lg border px-3 py-2 font-semibold text-[var(--marca)] hover:bg-[var(--fondo)]" title="Editar usuario" onClick={()=>abrir(u)}>⚙ Editar</button>{u.activo&&<button className="rounded-lg border border-red-200 px-3 py-2 font-semibold text-red-700" onClick={()=>void eliminar(u)}>Eliminar</button>}</div></td></tr>)}</tbody></table></div></section>
}

function EditorUsuario({usuario,perfiles,permisos,cerrar,recargar,informar}:{usuario:Usuario;perfiles:Perfil[];permisos:Permiso[];cerrar:()=>void;recargar:()=>Promise<void>;informar:(m:string)=>void}){
 const[activo,setActivo]=useState(usuario.activo),[admin,setAdmin]=useState(usuario.es_administrador),[perfilIds,setPerfilIds]=useState(usuario.perfil_ids),[permisoIds,setPermisoIds]=useState(usuario.permiso_ids),[mostrarClave,setMostrarClave]=useState(false),[clave,setClave]=useState("");const porModulo=useMemo(()=>Object.groupBy(permisos,p=>p.modulo),[permisos]);
 async function guardar(){const r=await fetch(`${apiUrl}/administracion/accesos/usuarios/${usuario.id}/accesos`,{method:"PUT",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({activo,es_administrador:admin,perfil_ids:perfilIds,permiso_ids:permisoIds})});const d=await r.json();if(!r.ok){informar(d.detail??"NO SE PUDO MODIFICAR");return}informar("USUARIO MODIFICADO");await recargar();cerrar()}
 async function resetear(e:FormEvent){e.preventDefault();const r=await fetch(`${apiUrl}/administracion/accesos/usuarios/${usuario.id}/restablecer-contrasena`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({contrasena_temporal:clave})});if(!r.ok){const d=await r.json();informar(d.detail??"NO SE PUDO RESTABLECER");return}informar("CONTRASEÑA RESTABLECIDA; DEBERA CAMBIARLA AL INGRESAR");setMostrarClave(false);setClave("")}
 async function eliminar(){if(!window.confirm(`¿Eliminar el acceso de ${usuario.nombre_usuario}?`))return;const r=await fetch(`${apiUrl}/administracion/accesos/usuarios/${usuario.id}`,{method:"DELETE",credentials:"include"});if(!r.ok){const d=await r.json();informar(d.detail??"NO SE PUDO ELIMINAR");return}informar("USUARIO DESACTIVADO");await recargar();cerrar()}
 return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" role="dialog" aria-modal="true"><section className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 shadow-xl"><header className="flex justify-between border-b pb-4"><div><p className="text-xs text-[var(--marca)]">EDITAR USUARIO</p><h2 className="text-xl font-semibold">{usuario.nombre_usuario}</h2></div><button className="text-2xl" onClick={cerrar}>×</button></header><div className="mt-5 grid gap-5 md:grid-cols-2"><div><h3 className="text-sm font-semibold">Estado y tipo</h3><div className="mt-3 space-y-2"><Check texto="Usuario activo" valor={activo} cambiar={setActivo}/><Check texto="Administrador" valor={admin} cambiar={setAdmin}/></div><h3 className="mt-5 text-sm font-semibold">Perfiles</h3><div className="mt-2 space-y-2">{perfiles.map(p=><Check key={p.id} texto={p.nombre} valor={perfilIds.includes(p.id)} cambiar={v=>setPerfilIds(v?[...perfilIds,p.id]:perfilIds.filter(id=>id!==p.id))}/>)}</div></div><div><h3 className="text-sm font-semibold">Permisos individuales</h3><div className="mt-3 max-h-72 space-y-4 overflow-y-auto">{Object.entries(porModulo).map(([modulo,items])=><fieldset key={modulo}><legend className="text-xs font-semibold uppercase text-[var(--marca)]">{modulo.replaceAll("_"," ")}</legend>{items?.map(p=><Check key={p.id} texto={`${p.accion}: ${p.descripcion}`} valor={permisoIds.includes(p.id)} cambiar={v=>setPermisoIds(v?[...permisoIds,p.id]:permisoIds.filter(id=>id!==p.id))}/>)}</fieldset>)}</div></div></div><div className="mt-6 flex flex-wrap gap-3 border-t pt-5"><button className="rounded-xl bg-[var(--marca)] px-4 py-2 text-sm font-semibold text-white" onClick={()=>void guardar()}>Guardar cambios</button><button className="rounded-xl border px-4 py-2 text-sm" onClick={()=>setMostrarClave(!mostrarClave)}>Resetear contraseña</button><button className="rounded-xl border border-red-300 px-4 py-2 text-sm text-red-700" onClick={()=>void eliminar()}>Eliminar acceso</button></div>{mostrarClave&&<form className="mt-4 flex gap-2 rounded-xl bg-[var(--fondo)] p-3" onSubmit={resetear}><input className="min-w-0 flex-1 rounded-lg border p-2 text-sm" type="password" minLength={10} value={clave} onChange={e=>setClave(e.target.value)} placeholder="Nueva contraseña temporal" required/><button className="rounded-lg bg-[var(--marca)] px-3 text-sm text-white">Confirmar</button></form>}</section></div>
}

function Perfiles({perfiles,permisos,recargar,informar}:{perfiles:Perfil[];permisos:Permiso[];recargar:()=>Promise<void>;informar:(m:string)=>void}){const[nombre,setNombre]=useState(""),[descripcion,setDescripcion]=useState(""),[ids,setIds]=useState<string[]>([]);const porModulo=useMemo(()=>Object.groupBy(permisos,p=>p.modulo),[permisos]);async function crear(e:FormEvent){e.preventDefault();const r=await fetch(`${apiUrl}/administracion/accesos/perfiles`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({nombre,descripcion,permiso_ids:ids})});const d=await r.json();if(!r.ok){informar(d.detail??"NO SE PUDO CREAR");return}setNombre("");setDescripcion("");setIds([]);informar("PERFIL CREADO");await recargar()}return <div className="grid gap-5 xl:grid-cols-2"><form className="rounded-2xl border bg-white p-5" onSubmit={crear}><h2 className="text-lg font-semibold">Nuevo perfil</h2><Campo titulo="Nombre" valor={nombre} cambiar={setNombre}/><Campo titulo="Descripcion" valor={descripcion} cambiar={setDescripcion}/><div className="mt-4 max-h-80 space-y-4 overflow-y-auto">{Object.entries(porModulo).map(([m,items])=><fieldset key={m}><legend className="text-xs font-semibold uppercase">{m}</legend>{items?.map(p=><Check key={p.id} texto={p.descripcion} valor={ids.includes(p.id)} cambiar={v=>setIds(v?[...ids,p.id]:ids.filter(id=>id!==p.id))}/>)}</fieldset>)}</div><button className="mt-4 rounded-xl bg-[var(--marca)] px-4 py-2 text-sm text-white">Crear perfil</button></form><section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-semibold">Perfiles existentes</h2>{perfiles.map(p=><div className="mt-3 rounded-xl bg-[var(--fondo)] p-3 text-sm" key={p.id}><b>{p.nombre}</b><p>{p.descripcion||"SIN DESCRIPCION"}</p><small>{p.permiso_ids.length} permisos</small></div>)}</section></div>}
function Permisos({permisos}:{permisos:Permiso[]}){const grupos=Object.groupBy(permisos,p=>p.modulo);return <section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-semibold">Indice de permisos</h2><div className="mt-4 grid gap-4 lg:grid-cols-2">{Object.entries(grupos).map(([m,items])=><article className="rounded-xl bg-[var(--fondo)] p-4" key={m}><h3 className="text-sm font-semibold uppercase text-[var(--marca)]">{m.replaceAll("_"," ")}</h3>{items?.map(p=><p className="mt-2 text-sm" key={p.id}><b>{p.accion}</b> · {p.descripcion}</p>)}</article>)}</div></section>}
function Campo({titulo,valor,cambiar,tipo="text"}:{titulo:string;valor:string;cambiar:(v:string)=>void;tipo?:string}){return <label className="mt-3 block text-sm">{titulo}<input className="mt-1 w-full rounded-xl border p-2.5" type={tipo} value={valor} onChange={e=>cambiar(e.target.value)} minLength={tipo==="password"?10:undefined} required/></label>}
function Check({texto,valor,cambiar}:{texto:string;valor:boolean;cambiar:(v:boolean)=>void}){return <label className="flex items-start gap-2 py-1 text-sm"><input className="mt-1" type="checkbox" checked={valor} onChange={e=>cambiar(e.target.checked)}/><span>{texto}</span></label>}
