[alembic]
script_location = %(here)s/migrations
prepend_sys_path = %(here)s

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = consola

[formatters]
keys = generico

[logger_root]
level = WARN
handlers = consola
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_consola]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generico

[formatter_generico]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
